<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<OutputType>Library</OutputType>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <RootNamespace>$(RootNamespace).Blazor</RootNamespace>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.AutoMapper" />
		<PackageReference Include="ByteLabs.Foundations.AspNetCore.Components.Web.Theming" />
		<PackageReference Include="ByteLabs.Foundations.AspNetCore.Components.FluentDesignUI.Web" />
	</ItemGroup>

	
	<ItemGroup>
		<ProjectReference Include="..\..\..\..\modules\Accounting\src\Blazor\Accounting.Blazor.csproj" />
		<ProjectReference Include="..\..\..\..\modules\Payables\src\Blazor\Payables.Blazor.csproj" />
		<ProjectReference Include="..\..\..\..\modules\Recevables\src\Blazor\Recevables.Blazor.csproj" />
		<ProjectReference Include="..\Application.Abstractions\FinanceServicesService.Application.Abstractions.csproj" />
	</ItemGroup>
</Project>
