<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.Ddd.Application.Abstractions" />
		<PackageReference Include="ByteLabs.Foundations.Authorization" />
		<PackageReference Include="ByteLabs.PlatformServices.AuditLogging.Application.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain.Abstractions\FinanceServicesService.Domain.Abstractions.csproj" />
	</ItemGroup>

</Project>
