<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(CurrentTargetFramework)</TargetFramework>
		<UseXunit>true</UseXunit>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="bunit" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Blazor\Recevables.Blazor.csproj" />
	  <ProjectReference Include="..\Domain.Context.Tests\Recevables.Domain.Context.Tests.csproj" />
	</ItemGroup>

</Project>
