<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(CurrentTargetFramework)</TargetFramework>
		<UseXunit>true</UseXunit>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Application\Payables.Application.csproj" />
	  <ProjectReference Include="..\Domain.Tests\Payables.Domain.Tests.csproj" />
	</ItemGroup>

</Project>
