<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\modules\Accounting\src\HttpApi.Client\Accounting.HttpApi.Client.csproj" />
		<ProjectReference Include="..\..\..\..\modules\Payables\src\HttpApi.Client\Payables.HttpApi.Client.csproj" />
		<ProjectReference Include="..\..\..\..\modules\Recevables\src\HttpApi.Client\Recevables.HttpApi.Client.csproj" />
		<ProjectReference Include="..\Application.Abstractions\FinanceServicesService.Application.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.Http.Client" />
	</ItemGroup>

</Project>
