<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application.Abstractions\FinanceServicesService.Application.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.Http.Client" />
	</ItemGroup>

</Project>
