<Project>
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

	<PropertyGroup>
		<ProductFeatureGroup>Saas</ProductFeatureGroup>
        <RootNamespace>ByteLabs.FinanceServices.$(ProductName).$(ProductFeatureGroup)</RootNamespace>
	</PropertyGroup>

</Project>
