<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
        <RootNamespace>$(RootNamespace).Domain</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Platform.Foundations.Domain.Context" />
		<PackageReference Include="ByteLabs.Foundations.DataFactory.Data.PlatformMigrator"  />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\AdministrationService.Domain.csproj" />
	</ItemGroup>

</Project>
