<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(CurrentTargetFramework)</TargetFramework>
		<UseXunit>true</UseXunit>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>

	<ItemGroup>
    <None Remove="appsettings.json" />
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <None Remove="appsettings.secrets.json" />
    <Content Include="appsettings.secrets.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ByteLabs.Foundations.Autofac" />
    <PackageReference Include="ByteLabs.Foundations.Authorization" />
    <PackageReference Include="ByteLabs.Foundations.TestFactory.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Domain\IdentityService.Domain.csproj" />
  </ItemGroup>

</Project>
