<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<OutputType>Library</OutputType>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <RootNamespace>$(RootNamespace).Blazor</RootNamespace>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.AspNetCore.Components.WebAssembly.Theming" />
		<PackageReference Include="ByteLabs.Platform.Foundations.Blazor.WebAssembly" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Blazor\AdministrationService.Blazor.csproj" />
		<ProjectReference Include="..\HttpApi.Client\AdministrationService.HttpApi.Client.csproj" />
	</ItemGroup>

</Project>
