<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
        <RootNamespace>$(RootNamespace).Domain</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.DataFactory.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Payables.Domain.csproj" />
	</ItemGroup>

</Project>
