<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<IsAspireSharedProject>true</IsAspireSharedProject>
		<ProductFeatureGroup>Shared</ProductFeatureGroup>
        <RootNamespace>ByteLabs.FinanceServices.Hosting.AspNetCore</RootNamespace>

    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
		<PackageReference Include="Aspire.StackExchange.Redis" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="ByteLabs.Aps.Hosting.AspNetCore" />
		<PackageReference Include="ByteLabs.Foundations.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shared.Hosting\Shared.Hosting.csproj" />
	</ItemGroup>

</Project>
