<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.PlatformServices.Account.Admin.HttpApi.Client" />
		<PackageReference Include="ByteLabs.Platform.Foundations.HttpApi.Client"  />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application.Abstractions\AdministrationService.Application.Abstractions.csproj" />
	</ItemGroup>

</Project>
