<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<IsAspireSharedProject>true</IsAspireSharedProject>
		<ProductFeatureGroup>Shared</ProductFeatureGroup>
        <RootNamespace>ByteLabs.FinanceServices</RootNamespace>
    </PropertyGroup>

</Project>