<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$(MSBuildThisFileDirectory)/StylingAnalyzers.targets" />

  <PropertyGroup>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(IntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

</Project>