<Project>
	<Import Project="$(MSBuildThisFileDirectory)/common.secrets.props" />
	<PropertyGroup>
		<TargetFramework>$(CurrentTargetFramework)</TargetFramework>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
		
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>$(MSBuildProjectName)</RootNamespace>

		<IncludeInDiagrams>true</IncludeInDiagrams>

		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>

	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Logs\**" />
		<Content Remove="Logs\**" />
		<EmbeddedResource Remove="Logs\**" />
		<None Remove="Logs\**" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
	</ItemGroup>
	
</Project>