<Project>
	<Import Project="$(MSBuildThisFileDirectory)/common.test.props" />
	
	<PropertyGroup>
		<WarningsAsErrors>$(WarningsAsErrors);xUnit1048</WarningsAsErrors>
	    <OutputType>Exe</OutputType>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="xunit.v3"  PrivateAssets="All" />
		<PackageReference Include="xunit.runner.visualstudio" VersionOverride="3.1.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit"/>
	</ItemGroup>

	<ItemGroup>
		<Content Include="$(MSBuildThisFileDirectory)/xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	
</Project>