<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
        <RootNamespace>$(RootNamespace).Domain</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Platform.Foundations.Domain" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain.Abstractions\AdministrationService.Domain.Abstractions.csproj" />
	</ItemGroup>

</Project>
