<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.Ddd.Domain.Abstractions" />
		<PackageReference Include="ByteLabs.PlatformServices.SaaS.Domain.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\shared\Shared.Settings\Shared.Settings.csproj" />
	</ItemGroup>

</Project>