<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(CurrentTargetFramework)</TargetFramework>
		<UseXunit>true</UseXunit>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Application\FinanceServicesService.Application.csproj" />
	  <ProjectReference Include="..\Domain.Tests\FinanceServicesService.Domain.Tests.csproj" />
	</ItemGroup>

</Project>
