<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../../'))" />

    <PropertyGroup>
        <ProductName>Recevables</ProductName>
        <RootNamespace>ByteLabs.FinanceServices.$(ProductName)</RootNamespace>
    </PropertyGroup>

</Project>