namespace ByteLabs.FinanceServices.Services.FinanceServices.Testing;

public abstract class FinanceServicesServiceAcceptanceTestBase : FinanceServicesServiceTestBase<FinanceServicesServiceAcceptanceTestModule>
{
}
