<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultNetCoreTargetFramework)</TargetFrameworks>
		<IsPackable>false</IsPackable>
        <RootNamespace>$(RootNamespace).Domain</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.Foundations.DataFactory.EntityFrameworkCore.PostgreSql" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Domain.Context\SaasService.Domain.Context.csproj" />
	</ItemGroup>



</Project>
