<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.PlatformServices.Identity.Application.Abstractions" />
		<PackageReference Include="ByteLabs.PlatformServices.Account.Admin.Application.Abstractions" />
		<PackageReference Include="ByteLabs.PlatformServices.AuditLogging.Application.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ByteLabs.PlatformServices.Security.IdentityServer.Application.Abstractions" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Domain.Abstractions\IdentityService.Domain.Abstractions.csproj" />
	</ItemGroup>

</Project>
