<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(ClientCompatibility)</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="ByteLabs.Platform.Foundations.Domain.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\shared\Shared.Settings\FinanceServices.Shared.Settings.csproj" />
	</ItemGroup>

</Project>
